### PR TITLE
added analysis based only on data from online workshops in 2020-2021

### PR DESCRIPTION
**Pull request by naoe-tatara**
based on the analysis jupyter notebook, made a new notebook to analyze only surveys relevant to online workshops.

### CODE REVIEW

**Comment by bast** [comment]
Thank you for the work. We can merge this.

One thing we could improve now or in future is that by copying the notebook we introduced a lot of code duplication. Most of the code is the same between the notebook and the only difference are file names and few notes. This means that in future, maintenance will be more difficult since changes need to be ported from one to the other.

But what we can also do is to merge and document this problem in an issue.

**Comment by naoe-tatara** [comment]
Thank you for the great point, @bast !
If it can be waited until the end of 19th Sep, I would like to work on it.

**Comment by bast** [comment]
It can for sure wait until then. Thanks again for your work on this.

**Comment by naoe-tatara** [comment]
I could not manage to work on pre-workshop survey, as I used up my available time by 19th Sep for the post-workshop survey.  If anyone else could jump in, I appreciate the help. Thanks.

**Comment by naoe-tatara** [comment]
@bast, hope this is good enough. I did not implement all the figures from responses for online workshops in README, but I only mentioned that they can be seen from the Jupyter Notebook. Also they are in figures folder with *-online.png. 
Some questions were new and only surveys for online workshops covered.

**Comment by bast** [comment]
Thank you!

**Pull request merged**
